# This is a basic workflow to help you get started with Actions

name: Documentation Generation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
      # Runs a single command using the runners shell
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      
      # Runs a single command using the runners shell
    - name: npm install
      run: npm install
    - name: install lix globally
      run: npm install --global lix
      # Downloads lix dependencies
    - name: lix download
      run: lix download

    # Runs a single command using the runners shell
    - name: Generate Documentation
      run: npm run gendoc
      
      # Runs a single command using the runners shell
    - name: Create Documentation
      run: npm run createdoc

